<?php

return [
    'review_passwordless' => (bool) env('DRSAM_REVIEW_PASSWORDLESS', false),
    'module_priorities' => [
        'superadmin' => 'high',
        'institution' => 'high',
        'unit' => 'high',
        'operational' => 'high',
        'operational_outpatient' => 'high',
        'external_pharmacy' => 'high',
        'doctor' => 'high',
        'patient' => 'high',
        'insurance_advisor' => 'high',
        'insurance_health' => 'medium',
        'digital_pharmacy' => 'medium',
        'orders' => 'medium',
        'provider_npt' => 'high',
        'provider_import' => 'medium',
        'provider_medicines' => 'medium',
        'provider_clinical_labs' => null,
        'messenger' => 'high',
    ],
    'modules' => [
        'superadmin' => [
            'label' => 'Modulo superadministrador',
            'target' => 'superadmin.dashboard',
            'route' => 'superadmin.dashboard',
            'roles' => ['superadmin'],
        ],
        'institution' => [
            'label' => 'Modulo institucion',
            'target' => 'institution.dashboard',
            'route' => 'institution.dashboard',
            'roles' => ['superadmin', 'admin', 'institution'],
        ],
        'unit' => [
            'label' => 'Modulo de unidad',
            'target' => 'unit.dashboard',
            'route' => 'unit.dashboard',
            'roles' => ['superadmin', 'admin', 'institution', 'unit'],
        ],
        'operational' => [
            'label' => 'Area operativa',
            'target' => 'operational.dashboard',
            'route' => 'operational.dashboard',
            'roles' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
        ],
        'operational_outpatient' => [
            'label' => 'Area Operativa Consulta Externa',
            'target' => 'outpatient.dashboard',
            'route' => 'outpatient.dashboard',
            'roles' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
        ],
        'external_pharmacy' => [
            'label' => 'Area Operativa Farmacia',
            'target' => 'external-pharmacy.dashboard',
            'route' => 'external-pharmacy.dashboard',
            'roles' => ['superadmin', 'admin', 'operational'],
        ],
        'digital_pharmacy' => [
            'label' => 'Farmacia Digital',
            'target' => 'pharmacy.dashboard',
            'route' => 'pharmacy.dashboard',
            'roles' => ['superadmin', 'admin', 'operational'],
        ],
        'orders' => [
            'label' => 'Pedidos paciente',
            'target' => 'orders.index',
            'route' => 'orders.index',
            'roles' => ['superadmin', 'admin', 'operational'],
        ],
        'insurance_health' => [
            'label' => 'Aseguradora salud',
            'target' => 'insurance.dashboard',
            'route' => 'insurance.dashboard',
            'roles' => ['superadmin', 'admin', 'insurance_admin', 'medical_auditor', 'patient_coordinator', 'delivery_coordinator', 'hospital_coordinator', 'billing', 'read_only', 'insurance_advisor'],
        ],
        'doctor' => [
            'label' => 'Modulo medico',
            'target' => 'doctor.dashboard',
            'route' => 'doctor.dashboard',
            'roles' => ['superadmin', 'admin', 'doctor'],
        ],
        'patient' => [
            'label' => 'Modulo paciente',
            'target' => 'patient.dashboard',
            'route' => 'patient.dashboard',
            'roles' => ['superadmin', 'admin', 'patient'],
        ],
        'insurance_advisor' => [
            'label' => 'Asesor de seguros GMM',
            'target' => 'insurance-advisor.dashboard',
            'route' => 'insurance-advisor.dashboard',
            'roles' => ['superadmin', 'admin', 'insurance_advisor'],
        ],
        'provider_npt' => [
            'label' => 'Proveedor NPT',
            'target' => 'provider.npt.dashboard',
            'route' => 'provider.npt.dashboard',
            'roles' => ['superadmin', 'admin', 'provider'],
        ],
        'provider_import' => [
            'label' => 'Proveedor importacion',
            'target' => 'provider.import.dashboard',
            'route' => 'provider.import.dashboard',
            'roles' => ['superadmin', 'admin', 'provider'],
        ],
        'provider_medicines' => [
            'label' => 'Distribuidor de medicamentos',
            'target' => 'provider.medicines.dashboard',
            'route' => 'provider.medicines.dashboard',
            'roles' => ['superadmin', 'admin', 'provider'],
        ],
        'provider_clinical_labs' => [
            'label' => 'Proveedor analisis clinicos',
            'target' => 'provider.clinical-labs.dashboard',
            'route' => 'provider.clinical-labs.dashboard',
            'roles' => ['superadmin', 'admin', 'provider'],
        ],
        'messenger' => [
            'label' => 'Mensajero',
            'target' => 'messenger.dashboard',
            'route' => 'messenger.dashboard',
            'roles' => ['superadmin', 'admin', 'messenger'],
        ],
    ],
    'demo_users' => [
        ['username' => 'superadmin', 'name' => 'Superadministrador', 'role' => 'superadmin', 'module' => 'superadmin'],
        ['username' => 'admin', 'name' => 'Administracion General', 'role' => 'admin', 'module' => 'institution'],
        ['username' => 'institucion', 'name' => 'Imss Bienestar Estado de Mexico', 'role' => 'institution', 'module' => 'institution', 'external_id' => 'inst-portal'],
        ['username' => 'angeles', 'name' => 'Operadora de Hospitales Angeles', 'role' => 'institution', 'module' => 'institution', 'external_id' => 'inst-angeles'],
        ['username' => 'imss.cdmx', 'name' => 'Imss Bienestar Ciudad de Mexico', 'role' => 'institution', 'module' => 'institution', 'external_id' => 'inst-imss-cdmx'],
        ['username' => 'imss.bienestar', 'name' => 'IMSS Bienestar Estado de Mexico', 'role' => 'institution', 'module' => 'institution', 'external_id' => 'inst-t2'],
        ['username' => 'unidad.demo', 'name' => 'Unidad medica demo', 'role' => 'unit', 'module' => 'unit'],
        ['username' => 'op.enfermeria', 'name' => 'Responsable de Enfermeria', 'role' => 'operational', 'module' => 'operational'],
        ['username' => 'op.farmacia', 'name' => 'Responsable de Farmacia intrahospitalaria', 'role' => 'operational', 'module' => 'operational'],
        ['username' => 'op.farmacia.externa', 'name' => 'Responsable de Farmacia Externa', 'role' => 'operational', 'module' => 'external_pharmacy'],
        ['username' => 'farmacia.digital', 'name' => 'Operacion Farmacia Digital', 'role' => 'operational', 'module' => 'digital_pharmacy'],
        ['username' => 'aseguradora.salud', 'name' => 'Aseguradora Salud', 'role' => 'insurance_admin', 'module' => 'insurance_health'],
        ['username' => 'op.oncologia', 'name' => 'Operador Centro Oncologico', 'role' => 'operational', 'module' => 'operational'],
        ['username' => 'op.consulta', 'name' => 'Operador Consulta Externa', 'role' => 'operational', 'module' => 'operational_outpatient'],
        ['username' => 'proveedor', 'name' => 'Proveedor NPT', 'role' => 'provider', 'module' => 'provider_npt'],
        ['username' => 'proveedor.importacion', 'name' => 'Proveedor Importacion', 'role' => 'provider', 'module' => 'provider_import'],
        ['username' => 'proveedor.medicamentos', 'name' => 'Distribuidor de Medicamentos', 'role' => 'provider', 'module' => 'provider_medicines'],
        ['username' => 'proveedor.analisis', 'name' => 'Proveedor Analisis Clinicos', 'role' => 'provider', 'module' => 'provider_clinical_labs'],
        ['username' => 'mensajero', 'name' => 'Luis Hernandez', 'role' => 'messenger', 'module' => 'messenger'],
        ['username' => 'jimmy.carter', 'name' => 'Dr. Carter Jimmy', 'role' => 'doctor', 'module' => 'doctor'],
        ['username' => 'paciente', 'name' => 'Claudia Beatriz Salinas Vega', 'role' => 'patient', 'module' => 'patient'],
        ['username' => 'asesor.seguros', 'name' => 'Asesor Seguros GMM', 'role' => 'insurance_advisor', 'module' => 'insurance_advisor'],
    ],
];

