<?php

return [
    'orders.create' => ['superadmin', 'admin', 'patient', 'operational'],
    'pharmacy.orders.update' => ['superadmin', 'admin', 'operational'],
    'external_pharmacy.orders.update' => ['superadmin', 'admin', 'operational'],
    'messenger.routes.update' => ['superadmin', 'admin', 'messenger'],
    'operational.provider_requests.update' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'operational.patients.create' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'operational.service_requests.create' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'outpatient.appointments.create' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'outpatient.appointments.update' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'outpatient.rooms.manage' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'outpatient.calendar.manage' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'outpatient.prescriptions.manage' => ['superadmin', 'admin', 'institution', 'unit', 'operational'],
    'provider.requests.update' => ['superadmin', 'admin', 'provider'],
    'unit.appointments.update' => ['superadmin', 'admin', 'unit'],
    'unit.profile.update' => ['superadmin', 'admin', 'institution', 'unit'],
    'unit.operational_users.manage' => ['superadmin', 'admin', 'institution', 'unit'],
    'unit.doctors.manage' => ['superadmin', 'admin', 'institution', 'unit'],
    'unit.external_pharmacy.update' => ['superadmin', 'admin', 'institution', 'unit'],
    'unit.procedure_areas.manage' => ['superadmin', 'admin', 'institution', 'unit'],
    'institution.units.update' => ['superadmin', 'admin', 'institution'],
    'institution.units.create' => ['superadmin', 'admin', 'institution'],
    'institution.services.manage' => ['superadmin', 'admin', 'institution'],
    'institution.medications.manage' => ['superadmin', 'admin', 'institution'],
    'institution.specialties.manage' => ['superadmin', 'admin', 'institution'],
    'insurance_advisor.policies.update' => ['superadmin', 'admin', 'insurance_advisor'],
    'superadmin.modules.update' => ['superadmin'],
    'superadmin.users.update' => ['superadmin'],
    'superadmin.catalogs.manage' => ['superadmin'],
    'superadmin.settings.update' => ['superadmin'],
];
