<?php

return [
    [
        'category' => 'Atención ambulatoria',
        'name' => 'Consulta externa',
        'spaces' => 'Consultorios generales y de especialidad',
        'equipment' => 'Mesas de exploración, básculas, baumanómetros, equipos de diagnóstico',
    ],
    [
        'category' => 'Atención de urgencias',
        'name' => 'Urgencias',
        'spaces' => 'Valoración, cubículos de atención, sala de reanimación',
        'equipment' => 'Camillas, monitores, desfibriladores, carros de reanimación',
    ],
    [
        'category' => 'Atención de urgencias',
        'name' => 'Observación',
        'spaces' => 'Cubículos y estaciones de vigilancia',
        'equipment' => 'Camas, camillas, monitores, bombas de infusión',
    ],
    [
        'category' => 'Hospitalización',
        'name' => 'Hospitalización general',
        'spaces' => 'Habitaciones individuales y compartidas, estaciones de enfermería',
        'equipment' => 'Camas hospitalarias, monitores, bombas de infusión',
    ],
    [
        'category' => 'Cuidados críticos',
        'name' => 'Cuidados intensivos de adultos',
        'spaces' => 'Cubículos de terapia intensiva',
        'equipment' => 'Camas, ventiladores, monitores, bombas de infusión',
    ],
    [
        'category' => 'Cuidados críticos',
        'name' => 'Cuidados intensivos pediátricos',
        'spaces' => 'Cubículos pediátricos',
        'equipment' => 'Camas pediátricas, ventiladores, monitores',
    ],
    [
        'category' => 'Cuidados críticos',
        'name' => 'Cuidados intensivos neonatales',
        'spaces' => 'Espacios de atención neonatal',
        'equipment' => 'Incubadoras, cunas térmicas, ventiladores, monitores',
    ],
    [
        'category' => 'Cuidados críticos',
        'name' => 'Cuidados intermedios',
        'spaces' => 'Cubículos de vigilancia',
        'equipment' => 'Camas, monitores, bombas de infusión',
    ],
    [
        'category' => 'Atención quirúrgica',
        'name' => 'Quirófanos',
        'spaces' => 'Salas de cirugía y áreas de preparación',
        'equipment' => 'Mesas quirúrgicas, lámparas, máquinas de anestesia, electrocauterios',
    ],
    [
        'category' => 'Atención quirúrgica',
        'name' => 'Recuperación posanestésica',
        'spaces' => 'Cubículos de recuperación',
        'equipment' => 'Camas, camillas, monitores, equipos de oxigenoterapia',
    ],
    [
        'category' => 'Atención quirúrgica',
        'name' => 'Cirugía ambulatoria',
        'spaces' => 'Preparación, procedimientos y recuperación',
        'equipment' => 'Camillas, mesas quirúrgicas, monitores',
    ],
    [
        'category' => 'Atención obstétrica',
        'name' => 'Tococirugía y atención obstétrica',
        'spaces' => 'Valoración, labor, expulsión y cirugía obstétrica',
        'equipment' => 'Camas obstétricas, monitores fetales, cunas térmicas',
    ],
    [
        'category' => 'Procedimientos',
        'name' => 'Sala de procedimientos y curaciones',
        'spaces' => 'Cubículos de procedimientos menores',
        'equipment' => 'Camillas, lámparas, instrumental, carros de curación',
    ],
    [
        'category' => 'Procedimientos',
        'name' => 'Endoscopia',
        'spaces' => 'Salas de estudio y áreas de reprocesamiento',
        'equipment' => 'Endoscopios, torres de video, equipos de reprocesamiento',
    ],
    [
        'category' => 'Procedimientos',
        'name' => 'Hemodinamia',
        'spaces' => 'Sala de procedimientos y control',
        'equipment' => 'Angiógrafo, mesa de procedimientos, monitores',
    ],
    [
        'category' => 'Tratamientos especializados',
        'name' => 'Hemodiálisis',
        'spaces' => 'Estaciones de tratamiento y área técnica',
        'equipment' => 'Máquinas de hemodiálisis, sillones, sistema de tratamiento de agua',
    ],
    [
        'category' => 'Tratamientos especializados',
        'name' => 'Unidad de infusión y quimioterapia',
        'spaces' => 'Estaciones de aplicación y cubículos',
        'equipment' => 'Sillones, camas, bombas de infusión, monitores',
    ],
    [
        'category' => 'Tratamientos especializados',
        'name' => 'Radioterapia',
        'spaces' => 'Salas de tratamiento, planeación y control',
        'equipment' => 'Acelerador lineal y equipos asociados, según disponibilidad',
    ],
    [
        'category' => 'Diagnóstico',
        'name' => 'Imagenología',
        'spaces' => 'Salas de rayos X, ultrasonido, mastografía, tomografía y resonancia',
        'equipment' => 'Equipos de imagen correspondientes a cada sala',
    ],
    [
        'category' => 'Diagnóstico',
        'name' => 'Laboratorio clínico',
        'spaces' => 'Áreas de procesamiento y análisis',
        'equipment' => 'Analizadores, centrífugas, microscopios, refrigeradores',
    ],
    [
        'category' => 'Diagnóstico',
        'name' => 'Toma de muestras',
        'spaces' => 'Cubículos de extracción y recepción',
        'equipment' => 'Sillones, mesas auxiliares, equipos de conservación temporal',
    ],
    [
        'category' => 'Diagnóstico',
        'name' => 'Anatomía patológica',
        'spaces' => 'Procesamiento, corte y análisis de muestras',
        'equipment' => 'Procesadores de tejidos, micrótomos, microscopios',
    ],
    [
        'category' => 'Apoyo clínico',
        'name' => 'Banco de sangre o servicio de transfusión',
        'spaces' => 'Áreas según el alcance de su operación',
        'equipment' => 'Refrigeradores, congeladores, centrífugas y equipos de conservación',
    ],
    [
        'category' => 'Rehabilitación',
        'name' => 'Rehabilitación y terapia física',
        'spaces' => 'Gimnasio terapéutico y cubículos',
        'equipment' => 'Camillas, barras paralelas, bicicletas y equipos de terapia',
    ],
    [
        'category' => 'Rehabilitación',
        'name' => 'Terapia respiratoria',
        'spaces' => 'Cubículos de atención y evaluación',
        'equipment' => 'Espirómetros y equipos de apoyo respiratorio',
    ],
    [
        'category' => 'Prevención',
        'name' => 'Unidad de vacunación',
        'spaces' => 'Aplicación, observación y conservación',
        'equipment' => 'Refrigeradores, registradores de temperatura, termos',
    ],
    [
        'category' => 'Atención ambulatoria',
        'name' => 'Odontología',
        'spaces' => 'Consultorios y áreas de procedimientos',
        'equipment' => 'Unidades dentales, instrumental, equipos de imagen dental',
    ],
    [
        'category' => 'Servicios farmacéuticos',
        'name' => 'Farmacia hospitalaria',
        'spaces' => 'Almacenamiento, preparación de pedidos y dispensación',
        'equipment' => 'Anaqueles, refrigeradores, carros de distribución, equipos de cómputo',
    ],
    [
        'category' => 'Servicios farmacéuticos',
        'name' => 'Farmacia externa',
        'spaces' => 'Mostradores, almacenamiento y entrega',
        'equipment' => 'Anaqueles, refrigeradores, lectores de códigos, equipos de cómputo',
    ],
    [
        'category' => 'Servicios farmacéuticos',
        'name' => 'Central de mezclas estériles',
        'spaces' => 'Preparación, acondicionamiento y resguardo',
        'equipment' => 'Cabinas según preparación, refrigeradores, equipos de monitoreo ambiental',
    ],
    [
        'category' => 'Apoyo quirúrgico',
        'name' => 'Central de Equipos y Esterilización - CEYE',
        'spaces' => 'Lavado, preparación, esterilización y almacenamiento',
        'equipment' => 'Lavadoras, autoclaves, selladoras, mesas de trabajo',
    ],
    [
        'category' => 'Abasto',
        'name' => 'Almacén de medicamentos y material de curación',
        'spaces' => 'Recepción, almacenamiento y distribución',
        'equipment' => 'Estanterías, refrigeradores o cámaras frías, equipos de control ambiental',
    ],
    [
        'category' => 'Servicios de apoyo',
        'name' => 'Nutrición y cocina hospitalaria',
        'spaces' => 'Preparación, refrigeración y distribución',
        'equipment' => 'Cocinas, hornos, refrigeradores, carros térmicos',
    ],
    [
        'category' => 'Soporte técnico',
        'name' => 'Ingeniería biomédica y mantenimiento',
        'spaces' => 'Talleres y áreas de evaluación',
        'equipment' => 'Herramientas, analizadores, simuladores y equipos de medición',
    ],
    [
        'category' => 'Servicios generales',
        'name' => 'Lavandería, ropería y limpieza',
        'spaces' => 'Lavado, secado, resguardo y distribución',
        'equipment' => 'Lavadoras, secadoras, carros de ropa, equipos de limpieza',
    ],
    [
        'category' => 'Servicios de apoyo',
        'name' => 'Mortuorio',
        'spaces' => 'Recepción y resguardo',
        'equipment' => 'Cámaras de refrigeración, camillas de traslado',
    ],
];
